### ISSUE TITLE
Malformed HTML in navigation links on M3.2

### ISSUE THREAD

**Issue by logan-reynolds** [davidherney/moodle-format_onetopic#21]
When testing on Moodle 3.2 Boost theme, this format seems to be displaying the html structure as the title of each tab, caused by a problem with additional doublequote (and possibly other) characters. The text inside of the first tab shows as:

`"<div style="" class="tab_content marker "><span>Topic 0</span></div>"`

The anchor tag is being rendered as:

`<a class="nav-link active " title="Topic" 0="" id="yui_3_17_2_1_1485987452297_35"><div style="" class="tab_content marker "><span>Topic 0</span></div></a>`

If you edit the structure of the anchor tag, it displays properly:

`<a class="nav-link active " title="Topic 0" id="yui_3_17_2_1_1485987452297_35"><div style="" class="tab_content marker "><span>Topic 0</span></div></a>`

**Comment by sbourget** [comment]
I ran across the same issue a few weeks ago and found it was a specific issue with the boost theme.  (It was converting the HTML to text rather than displaying it as HTML)  I submitted a fix for this as MDL-57728 (https://tracker.moodle.org/browse/MDL-57728) which was merged last week.

Can you try upgrading your copy of Moodle 3.2 to at least build 3.2.1+ (Build: 20170202).  The tabs should be displayed properly once you upgrade.

**Comment by davidherney** [comment]
I close it because is not a onetopic bug and it was fixed in moodle.

Thx @sbourget
