### ISSUE TITLE
What does Use topic summary as template do?

### ISSUE THREAD

**Issue by Jarvil** [davidherney/moodle-format_onetopic#24]
Hello,

Coudn't leave a message to the news forum here (no posting allowed even when registered);

http://aprendeenlinea.udea.edu.co/lms/investigacion/mod/forum/view.php?id=964

So I ask here, what does settings "Use topic summary as template" do? The help text isn't helpfull and I don't understand it.

**Comment by davidherney** [comment]
Hi...

I check it and the "Questions and suggestions" forum is open to posts for enrolled users into the course.

About your question: When you enable the option "Use topic summary as template", you can put html at the topic summary and then is used as template, for example, in order to build special layouts. You put special tags for reference your resources, for example:
`<p>Read the <em>[[News]]</em> forum.</p>`
You can reference the **News forum** with this tag into the HTML. Also, when the course editing is disabled, the resources referenced is not listed, only included into the summary HTML.

It is usefully for example for use bootstrap controls for your section/topic layout.

I hope you find it useful

Saludos

**Comment by Jarvil** [comment]
Hello,

To which Topic's summary does the setting refer to? Topic 0 or Topic 1? @davidherney
