### ISSUE TITLE
Error upgrading to 3.3 version

### ISSUE THREAD

**Issue by Jarvil** [davidherney/moodle-format_onetopic#37]
Hello,

We tried to upgrade onetopic to version 3.3 but it failed with error;

` PHP Fatal error:  Call to undefined function format_topics_upgrade_hide_extra_sections() in /var/www/xxxx/course/format/onetopic/db/upgradelib.php on line 72`

**Comment by davidherney** [comment]
Hi...

I couldn't reproduce the issue. The upgrade process work fine in my environment. However, I include explicitly the file with the function to prevent the issue in another environments or releases (Only into MOODLE_33 branch).

Please, test again and comment this issue in order to merge into the main branch.

Saludos

**Comment by Jarvil** [comment]
Hello,

Thanks the file version works. Are you planning to support Moodle 3.5? It's soon here and it's LTS version.
