### ISSUE TITLE
topic with restricted access is not displayed for student

### ISSUE THREAD

**Issue by giselebrugger** [davidherney/moodle-format_onetopic#60]
Moodle: Moodle 3.5 (Build: 20180517)
onetopic: 2018010604
Theme tested: boost , fordson and moove

if a topic has access restriction  in the onetopic format is not displayed

See:
to access topic 5 the student should complete the poll (name: enquete)
![restricao1](https://user-images.githubusercontent.com/5620195/50689518-33240d80-1011-11e9-8f3c-f707959c6145.png)

but student does not visualize the restriction and does not have access to the topic

![topic2](https://user-images.githubusercontent.com/5620195/50689640-9f067600-1011-11e9-8cef-f6af4db25514.png)

and at the end the link to the top topic (topic 5)
![topico3](https://user-images.githubusercontent.com/5620195/50689682-d7a64f80-1011-11e9-8c01-f21b8b666d4d.png)

if the format of the course is the Topics or buttom for example the topic 5 is displayed with the access restrictions

Format: Button
![button](https://user-images.githubusercontent.com/5620195/50689918-ae39f380-1012-11e9-97ef-1bac82da70f9.png)

Format: Topic

![topic](https://user-images.githubusercontent.com/5620195/50689960-d590c080-1012-11e9-92ee-4dc06c328411.png)

**Comment by giselebrugger** [comment]
I made the following change:
I removed the access restriction from the topic
and put in each activity separately. This worked perfectly
![onetopicactivity](https://user-images.githubusercontent.com/5620195/50694202-64580a00-1020-11e9-89c6-7d8d5e5b6cee.png)

**Comment by jprovasnik** [comment]
In 3.4, using San Juan, if the course settings are set to "Hidden sections are completely invisible" then students do not see any of the restricted tab sections at all, even if the restriction eye is not clicked in that section. 

When the course settings are set to "Hidden Sections are Shown in Collapsed form" then the students always see the restricted tab sections, even if the restriction eye IS clicked in that section. 

Is this part of this bug? It's not expected behavior based on how other course formats work...

**Comment by marcospaulos** [comment]
Parabéns!

**Comment by davidherney** [comment]
I try to use generic moodle behaviors but some features are different between formats. Hidden tabs are specials for the onetopic format and the current behavior is intentional.

However, according to your suggestions, I added a help icon into the tabs with information about section available restrictions. This feature is now an option into the "Hidden sections" course setting parameter.

Thanks for your comments and please try it.

Saludos

**Comment by izendegi** [comment]
Hi David,

I've tried that new functionality and works fine for teachers, but students can't click on the help icon whatever the visibility of the restriction is set; shouldn't the icon be clickable by students at least if the visibility of the restriction is greyed-out or I've misunderstood it?

**Comment by davidherney** [comment]
@izendegi, are you sure? I test it in my installation and it work fine  to students. Do you have any error in the JS console? What theme you use?

**Comment by izendegi** [comment]
It happens to me on Moodle 3.8 with Boost and Fordson themes, and I don't see any errors in the console. 

I've tried both showing and hiding the restriction and for the students the help icon is never clickable, not logging as a student nor logging as a teacher and then switching the role.

**Comment by davidherney** [comment]
Thanks @izendegi...
You're right.
I checked with other themes and It is a problem with a CSS property.
I just published a new release fixing this.

Saludos

**Comment by izendegi** [comment]
Hi @davidherney 

Yes, the new release fixes it and works as expected, now the help icon is clickable for students when the restriction is not hidden.

Thanks!
